package hr.fer.zemris.java.hw05.db.lexer;

/**
 * Enumeration of token types generated by lexer.
 * @author ltomic
 *
 */

public enum TokenType {

	/**
	 * End of file
	 */
	EOF,
	/**
	 * Letters(surrounded by \")
	 */
	STRING,
	/**
	 * Symbols <, >, !, =
	 */
	SYMBOL,
	/**
	 * Sequence of letters
	 */
	TEXT
}
